branches:
  except:
  - /.*(.tmp)$/

language: rust

matrix:
  include:
  - os: osx
  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
    - cargo test

notifications:
  email:
    on_success: never

os: linux

rust:
- stable
- beta
- nightly

script:
- cargo test

sudo: false
