branches:
  except:
  - /.*(.tmp)$/

language: rust

notifications:
  email:
    on_success: never

os: linux

rust:
- stable
- beta

script:
- cargo test

matrix:
  include:
    - os: linux
    rust: nightly
    script:
      - cargo test --features nightly
      - cargo test

sudo: false
